# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: E2E on Chrome

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - feature/**
      - bugfix/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Validate env
        run: echo "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}"

      - name: Cache Cypress Binary
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Install Cypress 📥
        run: ./node_modules/cypress/bin/cypress install

      - name: Run e2e tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          build: npm run build
          start: npm start
          browser: chrome
          wait-on: 'http://localhost:3000'
