# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: E2E on Chrome

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - feature/**
      - bugfix/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.1.7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # - name: Build
      #   run: npm run build

      # - name: Run e2e tests
      #   run: npm run test:ci

      # - name: Run e2e tests
      #   uses: cypress-io/github-action@v4
      #   with:
      #     install: false
      #     build: npm run build
      #     start: npm start
      #     browser: chrome
      #     wait-on: 'http://localhost:3000'

      - name: Run e2e tests
        run: |
           ./node_modules/.bin/start-server-and-test start http://localhost:3000 cy:run

      # - name: Run e2e tests
      #   run: |
      #     npx cypress run

# jobs:
#   install:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [16.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     container: cypress/browsers:node12.18.3-chrome87-ff82

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Cache local node_modules
#         uses: actions/cache@v1
#         with:
#           path: node_modules
#           key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-modules-${{ github.ref }}-

#       - name: Setup pnpm
#         uses: pnpm/action-setup@v2.0.1
#         with:
#           version: 7.1.7

#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'pnpm'

#       - name: Install dependencies
#         run: pnpm install

#       # - name: Save build folder
#       #   uses: actions/upload-artifact@v2
#       #   with:
#       #     name: build
#       #     if-no-files-found: error
#       #     path: build

#       - name: Cypress install
#         uses: cypress-io/github-action@v4
#         with:
#           # Disable running of tests within install job
#           install: false
#           runTests: false
#           build: npm run build

#   cypress-run:
#     runs-on: ubuntu-latest
#     needs: install
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v4
#         with:
#           install: false
#           build: npm run build
#           start: npm start

# jobs:
#   install:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#     # strategy:
#     #   matrix:
#     #     node-version: [16.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      # - name: Setup pnpm
      #   uses: pnpm/action-setup@v2.0.1
      #   with:
      #     version: 7.1.7

#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'pnpm'

#       - name: Install dependencies
#         run: pnpm install

#       - name: Save build folder
#         uses: actions/upload-artifact@v2
#         with:
#           name: build
#           if-no-files-found: error
#           path: build

#       - name: Cypress install
#         uses: cypress-io/github-action@v4
#         with:
#           # Disable running of tests within install job
#           runTests: false
#           build: yarn build

#   cypress-run:
#     - name: Cypress run
#       runs-on: ubuntu-latest
#       steps:
#         - name: Cypress run
#           uses: cypress-io/github-action@v4
#           with:
#             install: false
#             working-directory: ./apps/next
#             browser: chrome
#             build: npm run build
#             start: npm run start -- --filter=next-app
#             wait-on: "http://localhost:3000"

#       # - name: Build
#       #   run: npm run build

#       # - name: Run e2e tests
#       #   run: npm run test:ci
