# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Successful Deploy Action Example

on: deployment_status

jobs:
  build:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: XYZ
        run: echo ${{ github.event.deployment_status.target_url }}
        env:
          DEPLOY_URL: ${{ github.event.deployment_status.target_url }}

